version: '3.0'

services:
  grafana:
    container_name: 'briangann-gauge-panel-catalog-review'
    build:
      context: ../.config
      args:
        grafana_version: ${GRAFANA_VERSION:-10.1.1}
    ports:
      - 3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/briangann-gauge-panel
      - ./provisioning:/etc/grafana/provisioning
